### ISSUE TITLE
유저 테이블 추가 및 jpa 엔티티 작성

### ISSUE THREAD

**Issue by wcorn** [wcorn/toy#21]
## Description
- database에 user 관련 테이블 추가
- jpa entity 작성
- docs 작성
## Todo
- [ ] user_info entity 작성
- [ ] admin_login entity 작성
- [ ] social_login entity 작성
- [ ] social_provider 작성
- [ ] 각 테이블 연결
- [ ] database docs 작성

**Comment by wcorn** [comment]
![image](https://github.com/user-attachments/assets/198f50d0-35be-4c32-94aa-6d6226dc88d6)
