### ISSUE TITLE
Test Code 작성 환경 구성

### ISSUE THREAD

**Issue by wcorn** [wcorn/toy#25]
## Description
공통으로 사용할 test class를 구현한다. 

## Todo
- [ ] controller test를 통합할 class 작성
- [ ] 그외 test 들을 통합할 class 작성
- [ ] test 설정 파일 작성
