### ISSUE TITLE
회원가입 기능을 구현한다.

### ISSUE THREAD

**Issue by wcorn** [wcorn/toy#29]
## Description
소셜 로그인 후 회원가입을 구현한다. 

## Todo
- [ ] guest -> user로 변경
- [ ] nickname, email을 client로부터 받는다.
- [ ] email의 경우 인증되었는지 확인한다.
- [ ] nickname의 경우 최소 2글자 최대 8글자까지 가능하다.
