### ISSUE TITLE
닉네임 중복 제거를 위한 기본 닉네임 설정

### ISSUE THREAD

**Issue by wcorn** [wcorn/toy#34]
## Description
유저 검색 및 구별을 위한 닉네임 중복제거
그를 위해 회원가입 시 초기 닉네임 설정

## Todo
- [ ] 카카오 소셜로그인의 닉네임 가져오는 부분 삭제
- [ ] 랜덤 닉네임 생성 및 적용
- [ ] UUID를 만들어 앞 부분만 짤라서 사용 및 혹시 모를 중복 제거를 위해 DB 접근
